name: Release
on:
  workflow_dispatch:

permissions:
  packages: write
  pull-requests: write
  contents: write
  issues: write
  id-token: write
  attestations: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.11.0
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: tsc client
        run: pnpm tsc:client

      - name: tsc server
        run: pnpm tsc:server

      # - name: Lint
      #   run: pnpm lint

      # - name: Test
      #   run: pnpm test

      - name: Build
        run: pnpm build

      - name: Zip dist
        run: zip -r dist.zip dist

      - name: Attest
        uses: actions/attest-build-provenance@v2.3.0
        with:
          subject-path: "dist/**/*"

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4.1.1
        env:
          HUSKY: 0
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: dist
          path: dist.zip
